package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

func newWorkflowCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workflow [file ...]",
		Short: "Print a paste-ready agent workflow template",
		Long: "Prints a block you can paste into the human-written section of your\n" +
			"context file. It tells coding agents to regenerate the repoctx tables\n" +
			"after code changes and to gate on `repoctx audit . --check`. Files\n" +
			"default to AGENTS.md.",
		Args: cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runWorkflow(cmd, args)
		},
	}
	return cmd
}

func runWorkflow(cmd *cobra.Command, files []string) error {
	fmt.Fprintln(cmd.OutOrStdout(), workflowBlock(files))
	return nil
}

func workflowBlock(files []string) string {
	if len(files) == 0 {
		files = []string{"AGENTS.md"}
	}
	names := make([]string, len(files))
	for i, f := range files {
		names[i] = "`" + f + "`"
	}
	gen := "repoctx generate ."
	if len(files) > 1 || files[0] != "AGENTS.md" {
		for _, f := range files {
			gen += " --file " + f
		}
	}
	return fmt.Sprintf(`## Repo Context Maintenance

The Commands and Modules tables between `+"`<!-- repoctx:start -->`"+` and
`+"`<!-- repoctx:end -->`"+` in %s are generated by repoctx from the code —
never hand-edit them.

After you change commands, scripts, dependencies, manifests, or move packages, run:
1. `+"`"+gen+"`"+`  — regenerate the code-derived tables
2. `+"`repoctx audit . --check`"+`  — fail if the context drifted

Fix anything `+"`repoctx audit`"+` reports before finishing the task.`, strings.Join(names, " and "))
}
